### ISSUE TITLE
Official release of 6.0.28 is available

### ISSUE THREAD

**Issue by liko9** [negativo17/unifi#9]
https://community.ui.com/releases/UniFi-Network-Controller-6-0-28/23c77a99-0957-449a-b3c0-58a37d4df81f

**Comment by scaronni** [comment]
There is also 6.0.27, which is official, but no other version since 6.0.23 is available in the main download page (https://www.ui.com/download/unifi/) and the controller itself shows that no updates are available.

Also, the releases in that page are packaged differently, there is no generic zip file for Linux distributions.

**Comment by scaronni** [comment]
The URL for the zip file can be constructed as all the others and still works. Not sure if i should stick with "official" updates in the main download page.
